@startuml

title __DNA's Class Diagram__\n

  package  {
    package com.java.tp {
      package com.java.tp.dna {
        class CodeGenetic {
            {static} + main()
        }
      }
    }
  }
  

  package  {
    package com.java.tp {
      package com.java.tp.dna {
        class Codon {
            - codon : Nucleotide[]
            - protein : String
            + Codon()
            + getCodon()
            + getProtein()
        }
      }
    }
  }
  

  package  {
    package com.java.tp {
      package com.java.tp.dna {
        class DNA {
            - brin : ArrayList<Nucleotide>
            + DNA()
            + DNA()
            + add()
            + brinToString()
            + brinDisplay()
            {static} + transcription()
            + brinOppose()
            + rnaString()
            + getBrin()
        }
      }
    }
  }
  

  package  {
    package com.java.tp {
      package com.java.tp.dna {
        class Nucleotide {
            - symbol : char
            - name : String
            - family : String
            + Nucleotide()
            + display()
            + getName()
            - setName()
            + getSymbol()
            - setSymbol()
            + getFamily()
            - setFamily()
            + getComplementaire()
            - setComplementaire()
        }
      }
    }
  }
  

  package  {
    package com.java.tp {
      package com.java.tp.dna {
        class RNA {
            - brin : ArrayList<Nucleotide>
            + RNA()
            + brinToString()
            + traduction()
            + getBrin()
        }
      }
    }
  }
  

  Nucleotide o-- Nucleotide : complementaire


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
