@startuml

title __SHOP's Class Diagram__\n

  package  {
    package com.java.shop {
      class Author {
          - firstName : String
          - name : String
          - publisher : String
          + Author()
          + getFirstName()
          + getName()
          + setName()
          + getPublisher()
          + setPublisher()
      }
    }
  }
  

  package  {
    package com.java.shop {
      class Book {
          - nbPage : int
          - publicationYear : String
          - taux : int
          + Book()
          + getNetPrice()
          + getTaux()
          + display()
          + getNbPage()
          + getPublicationYear()
      }
    }
  }
  

  package  {
    package com.java.shop {
      class CD {
          - nbTrack : int
          + CD()
          + display()
          + getNetPrice()
          + getNbTrack()
      }
    }
  }
  

  package  {
    package com.java.shop {
      class Cart {
          ~ hashset : HashSet<MediaRow>
          ~ totalPriceTTC : double
          + Cart()
          + add()
          + remove()
          + getTotalPriceTTC()
      }
    }
  }
  

  package  {
    package com.java.shop {
      class DVD {
          - zone : String
          + DVD()
          + display()
          + getNetPrice()
          + getZone()
      }
    }
  }
    package  {
       package com.java.shop {
         class Publisher {
             - name : String
             + Publisher()
         }
       }
     }
  

  package  {
    package com.java.shop {
      interface IAuthor {
          {abstract} + getFirstName()
          {abstract} + getName()
          {abstract} + setName()
          {abstract} + getPublisher()
          {abstract} + setPublisher()
      }
    }
  }
  

  package  {
    package com.java.shop {
      interface IBook {
          {abstract} + getNetPrice()
          {abstract} + getTaux()
          {abstract} + display()
          {abstract} + getNbPage()
          {abstract} + getPublicationYear()
      }
    }
  }
  

  package  {
    package com.java.shop {
      interface ICD {
          {abstract} + display()
          {abstract} + getNetPrice()
          {abstract} + getNbTrack()
      }
    }
  }
  

  package  {
    package com.java.shop {
      interface ICart {
          {abstract} + add()
          {abstract} + remove()
          {abstract} + getTotalPriceTTC()
      }
    }
  }
  

  package  {
    package com.java.shop {
      interface IDVD {
          {abstract} + display()
          {abstract} + getNetPrice()
          {abstract} + getZone()
      }
    }
  }
  

  package  {
    package com.java.shop {
      interface IMedia {
          {abstract} + display()
          {abstract} + getNetPrice()
          {abstract} + getId()
          {abstract} + getTitle()
          {abstract} + getPrice()
          {abstract} + getTaux()
          {abstract} + getGenre()
      }
    }
  }
  

  package  {
    package com.java.shop {
      interface IMediaRow {
          {abstract} + add()
          {abstract} + add()
          {abstract} + remove()
          {abstract} + remove()
      }
    }
  }
  

  package  {
    package com.java.shop {
      abstract class Media {
          - id : int
          - title : String
          - price : double
          - genre : String
          - authorList : ArrayList<Author>
          - taux : int
          + Media()
          + Media()
          + display()
          + getId()
          + getTitle()
          + getPrice()
          + getTaux()
          + getGenre()
      }
    }
  }
  

  package  {
    package com.java.shop {
      class MediaRow {
          ~ nbCopies : int
          + MediaRow()
          + add()
          + add()
          + remove()
          + remove()
      }
    }
  }
  

  package  {
    package com.java.shop {
      class ProgramShop {
          {static} + main()
      }
    }
  }
  

  Author -up-|> IAuthor
  Book -up-|> IBook
  Book -up-|> Media
  CD -up-|> ICD
  CD -up-|> Media
  Cart -up-|> ICart
  DVD -up-|> IDVD
  DVD -up-|> Media
  Media -up-|> IMedia
  MediaRow -up-|> IMediaRow
  MediaRow o-- Media : media
  Cart o-- MediaRow
  Media o-- Author
  Media --> Publisher
  Publisher o--> Media



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
